#!/usr/bin/env python3
"""Generate high-precision polynomial for log2(x) on [2,4] via Chebyshev interpolation."""

import mpmath as mp
import math

mp.mp.dps = 80

def chebyshev_nodes(n, a, b):
    """Chebyshev nodes on [a, b]."""
    nodes = []
    for k in range(n):
        t = mp.cos(mp.pi * (2*k + 1) / (2*n))
        x = (b + a) / 2 + (b - a) / 2 * t
        nodes.append(x)
    return nodes

def chebyshev_coefficients(f, n, a, b):
    """Compute Chebyshev coefficients for f on [a,b] with n terms."""
    nodes = chebyshev_nodes(n, a, b)
    fvals = [f(x) for x in nodes]
    coeffs = []
    for j in range(n):
        s = mp.mpf(0)
        for k in range(n):
            t = mp.cos(mp.pi * (2*k + 1) / (2*n))
            Tj = mp.cos(j * mp.acos(t))
            s += fvals[k] * Tj
        c = 2 * s / n
        if j == 0:
            c /= 2
        coeffs.append(c)
    return coeffs

def chebyshev_to_monomial(coeffs, a, b):
    """Convert Chebyshev coefficients on [a,b] to monomial coefficients in x."""
    n = len(coeffs)
    # First get monomial coefficients on [-1,1]
    # T_0 = 1, T_1 = t, T_{n+1} = 2t*T_n - T_{n-1}
    # Build monomial coefficients for each T_k
    mono = [mp.mpf(0)] * n
    # T_k as monomial coeffs in t
    T_prev = [mp.mpf(0)] * n
    T_prev[0] = mp.mpf(1)  # T_0 = 1
    T_curr = [mp.mpf(0)] * n
    T_curr[1] = mp.mpf(1)  # T_1 = t

    # Add contribution of T_0
    for i in range(n):
        mono[i] += coeffs[0] * T_prev[i]
    if n > 1:
        for i in range(n):
            mono[i] += coeffs[1] * T_curr[i]

    for k in range(2, n):
        T_next = [mp.mpf(0)] * n
        for i in range(n):
            if i > 0:
                T_next[i] += 2 * T_curr[i-1]
            T_next[i] -= T_prev[i]
        for i in range(n):
            mono[i] += coeffs[k] * T_next[i]
        T_prev = T_curr
        T_curr = T_next

    # Now mono[i] are coefficients of t^i where t = (2x - (a+b))/(b-a)
    # t = (2/(b-a)) * x - (a+b)/(b-a)
    # Substitute t = alpha*x + beta
    alpha = mp.mpf(2) / (b - a)
    beta = -(a + b) / (b - a)

    # Expand (alpha*x + beta)^k for each term
    result = [mp.mpf(0)] * n
    for k in range(n):
        # mono[k] * (alpha*x + beta)^k
        # binomial expansion
        binom = [mp.mpf(0)] * n
        binom[0] = mp.mpf(1)
        # Multiply by (alpha*x + beta) k times
        for _ in range(k):
            new_binom = [mp.mpf(0)] * n
            for i in range(n):
                new_binom[i] += beta * binom[i]
                if i > 0:
                    new_binom[i] += alpha * binom[i-1]
            binom = new_binom
        for i in range(n):
            result[i] += mono[k] * binom[i]

    return result

def eval_poly(coeffs, x):
    """Evaluate polynomial with monomial coefficients (x^0 first)."""
    s = mp.mpf(0)
    for i in reversed(range(len(coeffs))):
        s = s * x + coeffs[i]
    return s

f = lambda x: mp.log(x) / mp.log(2)
a, b = mp.mpf(2), mp.mpf(4)

print("Searching for n that gives >= 64 bits on [2,4] for log2...")
for n in range(15, 30):
    cheb_coeffs = chebyshev_coefficients(f, n, a, b)
    mono_coeffs = chebyshev_to_monomial(cheb_coeffs, a, b)

    # Check max error on a fine grid
    max_err = mp.mpf(0)
    for i in range(10001):
        x = a + (b - a) * i / 10000
        err = abs(eval_poly(mono_coeffs, x) - f(x))
        if err > max_err:
            max_err = err

    bits = -float(mp.log(max_err, 2))
    print(f"  n={n}: {bits:.2f} bits (max error: {float(max_err):.6e})")

    if bits >= 66:  # target a bit over 64 for safety margin
        degree = n - 1
        print(f"\n==> n={n} (degree {degree}) achieves {bits:.2f} bits")

        # Output Horner coefficients (highest degree first)
        print(f"\nHorner coefficients (x^{degree} to x^0):")
        horner = []
        for i in reversed(range(n)):
            print(f"  {float(mono_coeffs[i]):.34e}")
            horner.append(float(mono_coeffs[i]))

        print(f"\nRust code:")
        print(f"    fn generate_log_poly(&self) -> Vec<QuantumCell<F>> {{")
        print(f"        // generated by chebyshev interpolation, poly degree {degree}, precision bits: {bits:.2f}")
        print(f"        // Estimated max error: {float(max_err):.20e}")
        print(f"        let coef: Vec<F> = [")
        line = "            "
        for i, c in enumerate(horner):
            s = f"{c:.20e}"
            if i < len(horner) - 1:
                s += ", "
            if len(line) + len(s) > 100:
                print(line.rstrip())
                line = "            " + s
            else:
                line += s
        print(line.rstrip())
        print(f"        ].into_iter().map(|c| self.quantization(c)).collect();")
        print(f"")
        print(f"        coef.iter().map(|x| Constant(*x)).collect()")
        print(f"    }}")
        break
